# Generated by Django 3.0.8 on 2020-08-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200808_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Usersreged',
        ),
    ]
