# Generated by Django 3.1 on 2020-08-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200808_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usersreged',
        ),
    ]
