# Generated by Django 3.1 on 2020-09-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0002_auto_20200830_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='worked_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
