# Generated by Django 3.1 on 2020-09-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0003_auto_20200902_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type_id',
            field=models.TextField(default='Free'),
        ),
    ]
