# Generated by Django 3.1 on 2020-09-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0004_auto_20200904_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type_id',
            new_name='category',
        ),
    ]
