# Generated by Django 3.1 on 2020-09-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0009_auto_20200906_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.CharField(max_length=100),
        ),
    ]
