# Generated by Django 3.1 on 2020-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0010_auto_20200906_1344'),
    ]

