# Generated by Django 3.1 on 2020-09-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0011_auto_20200906_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='worked_hours',
        ),
    ]
