# Generated by Django 3.1 on 2020-09-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0012_auto_20200906_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='Free', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='worked_hours',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
