# Generated by Django 3.1 on 2020-09-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0013_auto_20200906_1715'),
    ]


