# Generated by Django 3.1 on 2020-09-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0017_auto_20200906_1720'),
    ]


